#!/usr/bin/env bash
# script to install ngnix
apt-get update
apt-get install nginx -y
#config ngnix
echo "server {
    listen 80;
    server_name localhost;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
# Restart Nginx without using systemctl
kill -HUP "$(pgrep nginx)"

# Output success message
echo "Nginx installed and configured. Listening on port 80 with 'Hello World!' response."
