#!/usr/bin/env bash
# install load balancer

sudo apt update
sudo apt install -y haproxy

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 151666-web-01 100.25.190.21:80 check
    server 151666-web-02 54.160.77.90:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "configured - Roundrobin On web-01 & web-02"

sudo service haproxy restart
echo "HAProxy configured successfully with round-robin load balancing for web-01 and web-02"
