#!/usr/bin/env bash
# This script displays numbers from 1 to 20

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "4"
			echo "Bad luck from China"
			;;
		9)
			echo "9"
			echo "Bad luck from Japan"
			;;
		17)
			echo "17"
			echo "Bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac

	((i++))
done
