#!/usr/bin/env bash
#script that configures an Ubuntu server

cp /etc/hosts ~/hosts.newhost
echo "127.0.0.2		localhost" > ~/hosts.newhost
echo "8.8.8.8		facebook.com" >> ~/hosts.newhost
cp -f ~/hosts.newhost /etc/hosts
